### ISSUE TITLE
link_id and uploadedByUserId are not set for file

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#143]
# How to reproduce
1. Drag and drop file into deepcase
2. See empty AsyncFile link
3. Look at storage table in hasura and find that there is your file but `link_id` and `uploadedByUserId` are not set ![image](https://user-images.githubusercontent.com/66206278/229739736-6bf5e141-0a9c-4185-970e-314c3e6145c7.png)
![image](https://user-images.githubusercontent.com/66206278/229740306-695b0386-888b-4419-a9a6-8e040e2c90f1.png)

**Comment by icecroc255** [comment]
I've fixed it yesterday
