### ISSUE TITLE
Why are not there `InsertHandler`, `UpdateHandler`, `DeleteHandler` types?

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#150]
Может было бы лучше, будь у нас типы InsertHandler/UpdateHandler/DeleteHandler и Handle
А то по хендлеру не понять для какой операции он создан

**Comment by Konard** [comment]
I don't think it is useful change. The same handler can be used for HandleInsert, HandleUpdate, HandleDelete. And there is enough information in HandleOperation types to determine the type of event to which handler is attached.
