### ISSUE TITLE
Why is `PackageIdentifier.dependencies` optional?

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#189]
### Describe the issue

https://github.com/deep-foundation/deeplinks/blob/59d116208ff65ab8cb8a483ae6441518efec1970/imports/packager.ts#L15

Why is `PackageIdentifier.dependencies` optional?

**Comment by FreePhoenix888** [comment]
@Konard's answer: because this field may not exist. For example core package does not have version right now

**Comment by Konard** [comment]
@FreePhoenix888 not only core package will be without dependencies, other packages may create isolated type system in the future.
