### ISSUE TITLE
Add deep.serial to sync handlers

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#290]
# Description
Imagine that we insert some link, then after some operations insert another link. If the second insertion will not be succesffuly executed and throw an error - the first insertion will not rollback. The most  consistent solution for sync handlers to not handle manual rollback is to use serial which can be done as rarely is possible

**Comment by Konard** [comment]
@FreePhoenix888 it is impossible to use more than one transaction in sync handlers. All insert/update/delete operation in sync handlers will be executed in single transaction. So this issue cannot be implemented. deep.serial will be never needed in sync handlers.
