### ISSUE TITLE
Initial support for handlers

### ISSUE THREAD

**Issue by ivansglazunov** [deep-foundation/deeplinks#7]
> After initial fake version, will create kuber balanced multilang versions of runtimes. But now need initial prototype.

- [x] IUD handlers by type
- [x] IUD handlers by selector
- [x] Cron handler
- [x] Port handler

**Comment by ivansglazunov** [comment]
- [x] hasura event-handler `/api/eh/links` calls on any links table operation, and call `link.type.string.value` in nodejs vm

**Comment by ivansglazunov** [comment]
https://discord.com/channels/739430470345031692/845445509379784714/894632815365324801

**Comment by ivansglazunov** [comment]
https://github.com/deep-foundation/deeplinks/issues/25 - Handler Selectors

**Comment by Konard** [comment]
![F98D766E-50A0-4C90-9EF2-DDE459A9B243](https://user-images.githubusercontent.com/1431904/158029246-aec46948-9b7f-4fb1-abd8-aeea0c14643e.jpeg)
![8DF19786-A62A-4143-A97A-D9FCEE4618F7](https://user-images.githubusercontent.com/1431904/158029259-66a200e5-fadb-4c87-b57b-e969f71b00a6.jpeg)
